name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      # Установка пакетов
      - name: Install packages
        run: yarn install
        
      # Создание переменных окружения
      - name: Create env
        run: |
          echo "${{ secrets.ENV_DEV_FILE }}" > .env.development

      # Запуск тестирования
      - name: Running testing
        run: yarn ci
        
      # Сборка приложения
      - name: Build app
        run: yarn deploy
