name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Установка зависимостей
        run: yarn install

      - name: Создание переменных окружения
        run: |
          echo "${{ secrets.ENV_DEV_FILE }}" > .env.development

      #- name: Запуск тестов
      #  run: yarn ci

      # Сборка приложения
      - name: Сборка приложения
        run: yarn build

  deploy:
    runs-on: ubuntu-latest

    needs:
      - testing

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Авторизация в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Создание переменных окружения
        run: |
          echo "${{ secrets.ENV_PROD_FILE }}" > .env.production

      - name: Сборка и пуш
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vanne-ns:latest
          build-args: ${{ secrets.ENV_PROD_FILE }}
